name: BankSystem CI Automation

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up JDK 25
        uses: actions/setup-java@v4
        with:
          java-version: '25'
          distribution: 'microsoft' # Hoặc 'temurin'
          cache: maven

      - name: Build with Maven (Compile & Test)
        run: mvn clean package

      - name: Archive Production Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: BankSystem-Build-Jar
          path: target/*.jar
          retention-days: 5